export const questions = [
  { id:1, answer:false,
    text:'Apakah benar bahwa AI dapat digunakan untuk menggantikan proses verifikasi langsung ke database resmi Sinta?',
    explanation:'AI hanya sebagai alat bantu, bukan pengganti verifikasi resmi. Pemeriksaan Sinta pada jurnal lebih akurat dilakukan langsung melalui website resmi Sinta.' },
  { id:2, answer:true,
    text:'Apakah benar bahwa AI boleh membantu menerjemahkan atau memperbaiki bahasa tulisan, tetapi tidak boleh menggantikan proses membaca dan memahami literatur?',
    explanation:'Proses membaca dan memahami literatur adalah bagian penting dari proses belajar yang tidak bisa digantikan oleh AI.' },
  { id:3, answer:true,
    text:'Apakah benar bahwa AI boleh digunakan untuk membantu menyusun outline atau merangkum materi, asalkan isi akhir tetap dikembangkan oleh mahasiswa sendiri?',
    explanation:'AI adalah alat bantu, bukan pengganti usaha. Verifikasi dan pengembangan isi tetap harus dilakukan secara manual oleh pengguna.' },
  { id:4, answer:false,
    text:'Apakah benar bahwa hasil yang diberikan AI selalu akurat dan dapat diterima tanpa diverifikasi?',
    explanation:'AI bukan sumber mutlak. Setiap jawaban AI wajib diverifikasi ulang dengan sumber yang kredibel.' },
  { id:5, answer:true,
    text:'Apakah benar bahwa mahasiswa boleh menggunakan AI untuk eksplorasi ide, tetapi tetap berkewajiban untuk memahami dan mempertanggungjawabkan isi yang ditulis?',
    explanation:'AI adalah alat bantu untuk eksplorasi dan pengembangan ide, bukan pengganti kemampuan berpikir, memahami, dan mempertanggungjawabkan isi tulisan.' },
  { id:6, answer:false,
    text:'Apakah benar jika kita menggunakan AI versi gratis, kita sama sekali tidak mendapatkan hasil analisis data yang mendalam atau jawaban yang akurat untuk tugas kuliah?',
    explanation:'Keterbatasan fitur memang ada, tetapi AI versi gratis sudah lebih dari cukup jika digunakan secara bijak. Kuncinya ada pada efisiensi prompting, misalnya menjelaskan outline dahulu lalu meminta penjelasan per poin.' },
  { id:7, answer:false,
    text:'Apakah benar jika jawaban AI sudah terlihat sangat akademis dan meyakinkan, kita bisa langsung menyetujuinya tanpa ragu?',
    explanation:'Pengguna yang bijak tidak mendewakan AI. AI sering terlihat pintar padahal isinya keliru. Jadikan jawaban AI sebagai hipotesis awal yang wajib diuji menggunakan buku atau jurnal resmi.' },
]
